# model
obs_len: 16
pred_len: 24
num_class: 3
nei_radius: [5, 2, 3, 2]
embed_size: 128
num_decode_layers: 2
scale: [0.6, 0.1, 0.3]

# train
lr: 0.0001
batch_size: 128
epoch: 100

# val
val_topK: 5

# test
test_topK: [1, 3, 5, 10]