# model
obs_len: 8
pred_len: 12
num_class: 2
nei_radius: [2, 3, 2]
embed_size: 128
num_decode_layers: 2
scale: [0.2, 0.6]

# train
lr: 0.0001
batch_size: 128
epoch: 200

# val
val_topK: 5

# test
test_topK: [1, 3, 5, 10]